config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'

  devise_for :users
  resources :projects do
    resources :tasks, shallow: true do
      resources :comments, except: [:index]
    end
    resources :comments, except: [:index]
  end
  resources :comments, except: [:index] do
    resources :comments, except: [:index]
  end
  resources :users
  resources :teams
  get '/admin', to: 'admin_page#admin'
  get '/admin/project', to: 'admin_page#project_page', as: 'admin_projects'
  get '/admin/statistic_user/:id(.:format)', to:'admin_page#user_statistic', as: 'admin_user_statistic'
  get '/admin/statistic_project/:id(.:format)', to:'admin_page#project_statistic', as: 'admin_project_statistic'

  #get ' /comments/:id(.:format)', to: 'tasks/comments', as: 'task_comment'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  belongs_to :project
  belongs_to :user, optional: true
  has_many :comments, as: :commentable, dependent: :destroy
  has_one_attached :image

  validates :title, presence: true, length: { minimum: 2 }
  validates :content, presence: true, length: { minimum: 10 }
  validates :status, inclusion: { in: ['not started ', 'begin', 'in progress', 'done'],
                                  message: 'it is not a status(not started, begin, in progress, done)' }, allow_nil: true
end

app/controllers/tasks/comments_controller.rb
# frozen_string_literal: true

module Tasks
  class CommentsController < CommentsController
    before_action :set_commentable

    private

    def set_commentable
      @commentable = Task.find(params[:task_id])
    end
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  load_and_authorize_resource
  before_action :find_task, only: %i[show edit destroy update]
  before_action :find_project, only: %i[index new create]

  before_action :set_team_info, only: %i[new edit update create]

  def index
    @tasks = @project.tasks
  end

  def new
    @task = @project.tasks.new
  end

  def create
    @task = @project.tasks.new(task_params)

    if @task.save
      redirect_to task_path(@task)
    else
      render :new
    end
  end

  def update
    if @task.update(task_params)
      redirect_to task_path(@task)
    else
      render :edit
    end
  end

  def destroy
    pr_id = @task.project
    @task.destroy
    redirect_to project_tasks_path(pr_id)
  end

  def show
    @user_email = 'No user'
    unless @task.user_id.nil?
      user = User.find_by_id(@task.user_id)
      @user_email = user.first_name + ' ' + user.last_name + ' - ' + user.email
    end

    project = Project.find_by_id(@task.project_id)

    @project_name = project.name
  end

  def edit
    # code here
  end

  private

  def task_params
    params.require(:task).permit(:title,
                                 :content,
                                 :image,
                                 :start_date,
                                 :due_date,
                                 :estimation,
                                 :user_id,
                                 :status)
  end

  def set_team_info
    @team_users = []
    unless @task.project.nil?
      @task.project.teams.each { |team| @team_users += team.users }
      @team_users = @team_users.each_with_object([]) { |user, arr| arr << [user.email, user.id] }
    end
  end

  def find_project
    @project = Project.find(params[:project_id])
  end

  def find_task
    @task = Task.find(params[:id])
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<div class="form form-group">
  <%= simple_form_for [@project, @task]  do |f| %>
    <div class="form-group">
      <label>Task title </label>
      <%=f.input :title, class: 'form-control', placeholder: "Title", label: false %>
    </div>
    <div class="form-group">
      <label>Task description</label>
      <%=f.input :content, as: :text, label: false, class: 'form-control', placeholder: "Description ..." %>
    </div>

    <div class="form-group">
      <label>Image</label>
      <%=f.file_field :image,label: false, class: 'form-control', placeholder: "Img" %>
    </div>

    <div class="form-group">
      <label>Task start date</label>
      <%=f.input :start_date, label: false, class: 'form-control'%>
    </div>

    <div class="form-group">
      <label>Task due date</label>
      <%=f.input :due_date, label: false, class: 'form-control' %>
    </div>

    <div class="form-group">
      <label>Task estimation</label>
      <%=f.input :estimation, label: false, class: 'form-control' %>
    </div>

    <div class="form-group">
      <label>Status (not started, begin, in progress, done)</label>
      <%=f.input :status, label: false, class: 'form-control' %>
    </div>

    <div class="form-group col">
      <label>User on task:</label>
      <%= f.input :user_id, collection:  @team_users, label: false, class: 'form-control'  %>
    </div>

    <%= f.button :submit, class: 'btn btn-outline-info btn-sm mt-3' %>
  <% end %>
</div>

app/views/tasks/_task.html.erb
<dl class="row">
  <dt class="col-sm-3">Title:</dt>
  <dd class="col-sm-9"><%= task.title %></dd>

  <dt class="col-sm-3">Project id:</dt>
  <dd class="col-sm-9"><%= task.project_id %></dd>

  <dt class="col-sm-3">User id: </dt>
  <dd class="col-sm-9"><%= task.user_id %></dd>

  <dt class="col-sm-3">Task status:</dt>
  <dd class="col-sm-9"><%= task.status %></dd>
</dl>
<%= link_to "Learn more", task_path(task), :class => "btn btn-outline-secondary btn-sm"%>
<hr>

app/views/tasks/edit.html.erb
<h3>Editing task</h3>

<%= render "form" %>

app/views/tasks/index.html.erb
<h2 class="d-flex justify-content-center mt-4 ">Project tasks</h2>
<p class="d-flex justify-content-center mb-3">Amount of task on project: <%= @tasks.count %></p>
<%= link_to "Create new task", new_project_task_path(@project,@task), :class =>"btn btn-outline-info btn-sm" %>
<hr>
<%= render @tasks  %>

app/views/tasks/new.html.erb
<h1>Creating new task</h1>

<%= render "form" %>

app/views/tasks/show.html.erb
<dl class="row">
  <dt class="col-sm-3">Title: </dt>
  <dd class="col-sm-9"><%= @task.title %></dd>

  <dt class="col-sm-3">Content: </dt>
  <dd class="col-sm-9"><%= @task.content  %></dd>

  <dt class="col-sm-3">Start date: </dt>
  <dd class="col-sm-9"><%=  @task.start_date%></dd>

  <dt class="col-sm-3">Due date:</dt>
  <dd class="col-sm-9"><%= @task.due_date  %></dd>

  <dt class="col-sm-3">Estimation: </dt>
  <dd class="col-sm-9"><%= @task.estimation %></dd>

  <dt class="col-sm-3">Project:</dt>
  <dd class="col-sm-9"><%= @project_name %></dd>

  <dt class="col-sm-3">User:</dt>
  <dd class="col-sm-9"><%= @user_email%></dd>

  <dt class="col-sm-3">Task status: </dt>
  <dd class="col-sm-9"><%= @task.status %></dd>
  <% if @task.image.attached? %>
    <div style="width: 400px">
    <dd class="col-sm-9"><%= image_tag(@task.image, style: "width: 100%") %></dd>
    </div>
  <% end %>
</dl>

<%= link_to "Edit", edit_task_path(@task), :class => 'btn btn-outline-info btn-sm' %>
<%= link_to "Delete", task_path(@task), method: :delete, data: {confirm: "Are you sure?"}, :class => 'btn btn-outline-danger btn-sm' %>

<hr>
<h3 class="mt-4" >Comments</h3>
<%= render partial: 'comments/form', locals: {commentable: @task} %>
<ul>
  <%= render partial: 'comments/comment', locals: {commentable: @task} %>
</ul>