config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'

  devise_for :users
  resources :projects do
    resources :tasks, shallow: true do
      resources :comments, except: [:index]
    end
    resources :comments, except: [:index]
  end
  resources :comments, except: [:index] do
    resources :comments, except: [:index]
  end
  resources :users
  resources :teams
  get '/admin', to: 'admin_page#admin'
  get '/admin/project', to: 'admin_page#project_page', as: 'admin_projects'
  get '/admin/statistic_user/:id(.:format)', to:'admin_page#user_statistic', as: 'admin_user_statistic'
  get '/admin/statistic_project/:id(.:format)', to:'admin_page#project_statistic', as: 'admin_project_statistic'

  #get ' /comments/:id(.:format)', to: 'tasks/comments', as: 'task_comment'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin_page_controller.rb
# frozen_string_literal: true

class AdminPageController < ApplicationController
  # load_and_authorize_resource class:  AdminPageController
  def admin
    @users = User.all.paginate(page: params[:page], per_page: 15)
  end

  def project_page
    @projects = Project.all.paginate(page: params[:page], per_page: 10)
  end

  def user_statistic
    @user = User.find_by_id(params[:id])
    @amount_of_task = @user.tasks.count
    @complete_tasks = @user.tasks.where({ status: 'done' })
    @incomplete_tasks = @user.tasks.where({ status: ['in progress', 'not started', 'begin', '', nil] })
  end

  def project_statistic
    @project = Project.find_by_id(params[:id])
    @amount_of_task = @project.tasks.count
    @complete_tasks = @project.tasks.where({ status: 'done' })
    @incomplete_tasks = @project.tasks.where({ status: ['in progress', 'not started', 'begin', '', nil] })
  end
end

app/helpers/admin_page_helper.rb
module AdminPageHelper
end

app/views/admin_page/admin.html.erb
<h1>Statistic</h1>
<%= link_to "Go to project statistic", admin_projects_path, class: 'btn btn-sm btn-outline-secondary' %>
<hr>
<h3>User details:</h3>
<ol class = "col">

  <%@users.each do |user| %>
    <li><h5><%= link_to user.first_name+" "+user.last_name, admin_user_statistic_path(user), class: "text-reset" %></h5>
    </li>
  <% end %>
  <%= will_paginate @users,  renderer: BootstrapPagination::Rails %>
</ol>

app/views/admin_page/project_page.html.erb
<h1>Statistic</h1>
<%= link_to "Go to user statistic", admin_path, class: 'btn btn-sm btn-outline-secondary' %>
<hr>

<h3>Project details</h3>
<ol>
  <%@projects.each do |project| %>
    <li><h5><%= link_to project.name, admin_project_statistic_path(project), class: "text-reset" %></h5>
    </li>
  <% end %>
</ol>
<%= will_paginate @projects,  renderer: BootstrapPagination::Rails %>

app/views/admin_page/project_statistic.html.erb
<h3>Statistic for: <%= @project.name%></h3>
<hr>
<p>Amount of task on project: <strong><%= @amount_of_task %></strong> </p>
<br>
<p>Complete tasks: <strong><%= @complete_tasks.count %></strong> </p>
<ol class="p-3 mb-2 bg-success text-white">
  <%@complete_tasks.each do |task| %>
    <li class = "m-2 ml-4"><p><%= link_to task.title, task_path(task), class: "text-reset" %></p></li>
  <% end %>
</ol>
<br>

<p>Incomplete tasks: <strong><%= @incomplete_tasks.count %></strong> </p>
<ol class="p-3 mb-2 bg-danger text-white">
  <%@incomplete_tasks.each do |task| %>
    <li class = "m-2 ml-4"><p><%= link_to task.title, task_path(task), class: "text-reset" %></p></li>
  <% end %>
</ol>

app/views/admin_page/user_statistic.html.erb
<h3>Statistic for: <%= @user.first_name + "" + @user.last_name %></h3>
<hr>
<p>Amount of task on user: <strong><%= @amount_of_task %></strong> </p>
<br>
<p>Complete tasks: <strong><%= @complete_tasks.count %></strong> </p>
<ol class="p-3 mb-2 bg-success text-white">
<%@complete_tasks.each do |task| %>
  <li class = "m-2 ml-4"><p><%= link_to task.title, task_path(task), class: "text-reset" %></p></li>
<% end %>
</ol>
<br>

<p>Incomplete tasks: <strong><%= @incomplete_tasks.count %></strong> </p>
<ol class="p-3 mb-2 bg-danger text-white">
<%@incomplete_tasks.each do |task| %>
  <li class = "m-2 ml-4"><p><%= link_to task.title, task_path(task), class: "text-reset" %></p></li>
<% end %>
</ol>