config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'

  devise_for :users
  resources :projects do
    resources :tasks, shallow: true do
      resources :comments, except: [:index]
    end
    resources :comments, except: [:index]
  end
  resources :comments, except: [:index] do
    resources :comments, except: [:index]
  end
  resources :users
  resources :teams
  get '/admin', to: 'admin_page#admin'
  get '/admin/project', to: 'admin_page#project_page', as: 'admin_projects'
  get '/admin/statistic_user/:id(.:format)', to:'admin_page#user_statistic', as: 'admin_user_statistic'
  get '/admin/statistic_project/:id(.:format)', to:'admin_page#project_statistic', as: 'admin_project_statistic'

  #get ' /comments/:id(.:format)', to: 'tasks/comments', as: 'task_comment'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  has_many :tasks, dependent: :destroy
  has_and_belongs_to_many :teams
  has_many :comments, as: :commentable, dependent: :destroy

  validates :name, presence: true, length: { minimum: 2 }
  validates :summary, presence: true, length: { minimum: 10 }
end

app/controllers/projects/comments_controller.rb
# frozen_string_literal: true

module Projects
  class CommentsController < CommentsController
    before_action :set_commentable

    private

    def set_commentable
      @commentable = Project.find(params[:project_id])
    end
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  load_and_authorize_resource

  def index
    @projects = Project.all.paginate(page: params[:page], per_page: 10)
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project
    else
      render :new
    end
  end

  def show
    @project_teams = @project.teams.map { |team| team = team.name }
  end

  def update
    if @project.update(project_params)
      redirect_to @project
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path
  end

  private

  def project_params
    params.require(:project).permit(:name, :summary, :start_date, :end_date)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
 <div class="form form-group">
  <%= simple_form_for @project do |f| %>
    <div class="form-group">
      <label for="form_project_name">Project name</label>
      <%= f.input :name, label: false, id: 'form_project_name' ,class: 'form-control', placeholder: "Name" %>
    </div>

    <div class="form-group">
      <label for="form_project_description">Project description</label>
      <%= f.input :summary, as: :text, label: false, id: 'form_project_description', class: 'form-control', placeholder: "Description ..."  %>
    </div>

    <div class="form-group">
      <label>Project start date</label>
      <%= f.input :start_date,label: false, class: 'form-control' %>
    </div>

    <div class="form-group">
      <label>Project end date</label>
      <%= f.input :end_date, label: false, class: 'form-control' %>
    </div>

    <%= f.button :submit, class: 'btn btn-outline-info btn-sm mt-3' %>
  <% end %>
 </div>

app/views/projects/_project.html.erb
<hr>
<dl class="row">
  <dt class="col-sm-2">Project name: </dt>
  <dd class="col-sm-4"><%=project.name %></dd>

  <dt class="col-sm-1">Id:</dt>
  <dd class="col-sm-2"><%= project.id%></dd>

  <% if user_signed_in? %>
  <%= link_to "Learn more", project_path(project), :class => "btn btn-outline-secondary btn-sm"%>
  <% end %>
</dl>

app/views/projects/edit.html.erb
<h3>Edit project</h3>

<%= render "form" %>

app/views/projects/index.html.erb
<h2 class="d-flex justify-content-center mt-4 mb-3">All Projects </h2>

<p class="mb-4">Amount of projects: <%= @projects.count %> </p>
<% if user_signed_in? %>
<%= link_to "Create new project", new_project_path(@project), :class =>"btn btn-outline-info btn-sm" %>
<%end %>
<%= render @projects %>
<div class = 'm-4'>
<%= will_paginate @projects %>
</div>

app/views/projects/new.html.erb
<h2 class="d-flex justify-content-center mt-4 mb-3">Creating new project</h2>

<%= render "form" %>

app/views/projects/show.html.erb
<dl class="row">
  <dt class="col-sm-3">Project: </dt>
  <dd class="col-sm-9"><%= @project.name %></dd>

  <dt class="col-sm-3">Summary: </dt>
  <dd class="col-sm-9"><%= @project.summary %></dd>

  <dt class="col-sm-3">Project id: </dt>
  <dd class="col-sm-9"><%= @project.id %></dd>

  <dt class="col-sm-3">Start date:</dt>
  <dd class="col-sm-9"><%= @project.start_date %></dd>

  <dt class="col-sm-3">End date: </dt>
  <dd class="col-sm-9"><%= @project.end_date %></dd>

  <dt class="col-sm-3">Project teams:</dt>
  <dd class="col-sm-9">
      <% @project_teams.each do |team| %>
        <p> <%= team %> </p>
      <%end %>
  </dd>
</dl>
<%= link_to "Show project's tasks", project_tasks_path(@project), :class => "btn btn-outline-dark btn-sm mb-3" %> </br>
<%= link_to "Edit", edit_project_path(@project), :class => 'btn btn-outline-info btn-sm' %>
<%= link_to "Delete", project_path(@project), method: :delete, data: {confirm: "Are you sure?"}, :class => 'btn btn-outline-danger btn-sm' %>
<hr>
<h3 class="mt-4 mb-3" >Comments</h3>
<%= render partial: 'comments/form', locals: {commentable: @project}%>

  <ul>
    <%= render partial: 'comments/comment',  locals: {commentable: @project}%>
  </ul>