config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'

  devise_for :users
  resources :projects do
    resources :tasks, shallow: true do
      resources :comments, except: [:index]
    end
    resources :comments, except: [:index]
  end
  resources :comments, except: [:index] do
    resources :comments, except: [:index]
  end
  resources :users
  resources :teams
  get '/admin', to: 'admin_page#admin'
  get '/admin/project', to: 'admin_page#project_page', as: 'admin_projects'
  get '/admin/statistic_user/:id(.:format)', to:'admin_page#user_statistic', as: 'admin_user_statistic'
  get '/admin/statistic_project/:id(.:format)', to:'admin_page#project_statistic', as: 'admin_project_statistic'

  #get ' /comments/:id(.:format)', to: 'tasks/comments', as: 'task_comment'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Work manager</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <% if user_signed_in? %>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Projects",projects_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Teams",teams_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Users",users_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Profile", user_path(current_user), class: 'nav-link' if current_user %>
        </li>

        <li class="nav-item">
          <%= link_to link_to "Admin room", admin_path, class: 'nav-link' if can?(:use_admin_page, current_user) %>
        </li>


      </ul>
    </div>
      <%end %>
    <div class="nav-item pull-right">
      <% if user_signed_in? %>
        <%= link_to "log out", destroy_user_session_path, method: :delete, class: 'btn btn-sm btn-outline-secondary' %>
      <% else %>
        <%= link_to "Log in", new_user_session_path, class: 'btn btn-sm btn-outline-secondary' %>
        <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-sm btn-outline-secondary' %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "layouts/navbar" %>
  <div class="container mt-3">
    <%= yield %>
  </div>


  </body>
</html>